name: Build and Package App

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SAM_CLI_TELEMETRY: 0

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Semantic Release
              uses: go-semantic-release/action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              id: semantic


           

            - name: Install AWS SAM CLI
              uses: aws-actions/setup-sam@v2
              with:
                use-installer: true

            - name: Build SAW application
              
              run: |
                if [ ${{ steps.semantic.outputs.version }} > 0 ]; then
                  sam build -p
                fi
            