name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v1
        - run: bun install
        - run: bun run build
        - name: go-semantic-release
          id: semantic
          uses: ./
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
        